apiversion: cert-manager.io/v1
kind: Certificate
metadata:
  name: blue-green-certificate
  namespace: blue-green
spec:
  secretname: blue-green-certificate
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName:
    - bluegreenlive.81.co.ucll.cloud
    - bluegreenstaging.81.co.ucll.cloud
  dnsNames:
    - bluegreenlive.81.co.ucll.cloud
    - bluegreenstaging.81.co.ucll.cloud
