apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: http-scaler
spec:
  scaleTargetRef:
    kind: Rollout
    name: helm-guestbook
  triggers:
    - type: cron
      metadata:
        timezone: Asia/Kolkata
        start: 30 * * * *
        end: 45 * * * *
        desiredReplicas: "3"
