apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: http-scaler
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: {{ template "helm-guestbook.fullname" . }}
    namespace: {{ .Values.namespace }}
  triggers:
    - type: cron
      metadata:
        timezone: Europe/Paris
        start: 00 08 * * 1-5
        end: 00 18 * * 1-5
        desiredReplicas: "3"
