name: Production Workflow

on:
  release:
    types: [created, published]

jobs:
  test:
    name: building and testing image
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: ./nextjs-blog

      - name: Install dependencies
        run: |
          cd ./nextjs-blog
          npm install
        working-directory: ./nextjs-blog

      - name: Run tests
        run: |
          cd ./nextjs-blog
          npm test
        working-directory: ./nextjs-blog

  build:
    name: Build and Push the image
    runs-on: ubuntu-latest
    needs: test
    environment: prod

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: thomasvanopstal/cloud_next_prod:${{ github.sha }} , thomasvanopstal/cloud_next_prod:latest

  update:
    name: Update Helm Manifests
    runs-on: ubuntu-latest
    needs: build
    environment: prod

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Update Image Tag Values
        run: |
          chart_dir="chart/prod"
          new_image_tag=${{ github.sha }}

          # Update the values.yaml file with the new image tag
          sed -i "s/^  tag: .*/  tag: $new_image_tag/" "$chart_dir/values.yaml"

      - name: Commit the changes made
        run: |
          git config --global user.name 'ThomasVanOpstal'
          git config --global user.email 'thomas.vanopstal@outlook.be'
          git add .
          git commit -m "updating image tag"
          git push
