name: Qa Workflow

on:
  push:
    branches:
      - "main"
jobs:
  test:
    name: building and testing image
    runs-on: ubuntu-latest
    environment: qa
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: ./nextjs-blog

      - name: Install dependencies
        run: |
          cd ./nextjs-blog
          npm install
        working-directory: ./nextjs-blog

      - name: Run tests
        run: |
          cd ./nextjs-blog
          npm test
        working-directory: ./nextjs-blog

  build:
    name: Build and Push the image
    runs-on: ubuntu-latest
    needs: test
    environment: qa

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: thomasvanopstal/cloud_next_qa:${{ github.sha }} , thomasvanopstal/cloud_next_qa:latest

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    environment: qa

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'ThomasVanOpstal'
          git config --global user.email 'thomas.vanopstal@outlook.be'

      - name: Get tag
        id: get_tag
        run: |
          git branch --show-current
          git pull
          echo "version=v$(npm pkg get version | tr -d '\"')" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_tag.outputs.version  }}
          release_name: Release ${{ steps.get_tag.outputs.version }}
          draft: false
          prerelease: false

  update:
    name: Update Helm Manifests
    runs-on: ubuntu-latest
    needs: build
    environment: qa

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Update Image Tag Values
        run: |
          chart_dir="chart/qa"
          new_image_tag=${{ github.sha }}

          # Update the values.yaml file with the new image tag
          sed -i "s/^  tag: .*/  tag: $new_image_tag/" "$chart_dir/values.yaml"

      - name: Commit the changes made
        run: |
          git config --global user.name 'ThomasVanOpstal'
          git config --global user.email 'thomas.vanopstal@outlook.be'
          git add .
          git commit -m "updating image tag"
          git push
